const mongoose = require('mongoose');

const timetableSchema = new mongoose.Schema({

    day:{
        type:String,
        require:true
    },
    firstPeriod:[{
        subject:{
            type:String,
            required:true
        },
        startingTime:{
            type:String,
            required:true
        },
        endingTime:{
            type:String,
            required:true
        },
        tutor:{
            type:String,
            required:true
        }
    }
    ],
    secondPeriod:[{
        subject:{
            type:String,
            required:true
        },
        startingTime:{
            type:String,
            required:true
        },
        endingTime:{
            type:String,
            required:true
        },
        tutor:{
            type:String,
            required:true
        }
    }
    ],
    thirdPeriod:[{
        subject:{
            type:String,
            required:true
        },
        startingTime:{
            type:String,
            required:true
        },
        endingTime:{
            type:String,
            required:true
        },
        tutor:{
            type:String,
            required:true
        }
    }
    ],
    fourthPeriod:[{
        subject:{
            type:String,
            required:true
        },
        startingTime:{
            type:String,
            required:true
        },
        endingTime:{
            type:String,
            required:true
        },
        tutor:{
            type:String,
            required:true
        }
    }
    ],
    fifthPeriod:[{
        subject:{
            type:String,
            required:true
        },
        startingTime:{
            type:String,
            required:true
        },
        endingTime:{
            type:String,
            required:true
        },
        tutor:{
            type:String,
            required:true
        }
    }
    ]
})

const timetableCollection = new mongoose.model("timetableCollection",timetableSchema)
module.exports = timetableCollection